name: Build

on:
- push

jobs:
  default:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Use cached node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-v1-dependencies-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-v1-dependencies-

    - name: Install node_modules
      run: npm ci

    - name: Build Capacitor project
      run: npm run build

    #- name: Test web implementation
    #  working-directory: ./packages/plugin
    #  env:
    #    STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
    #    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    #  run: npm test

    - name: Install test app node_modules
      working-directory: ./demo/angular
      run: npm ci && npm run cap

    - name: Build test React app
      working-directory: ./demo/react
      run: npm ci && npm run build

    - name: Update & Sync Capacitor Project
      working-directory: ./demo/angular
      run: npx cap update android

    - name: Build Android Debug APK
      working-directory: ./demo/angular/android
      run: ./gradlew assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./demo/angular/android/app/build/outputs/apk/debug/app-debug.apk

  verify-android:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run verify:android
